### ISSUE TITLE
hi, friend , do you have the code book?

### ISSUE THREAD

**Issue by ming91915** [klm555/pbd-perform3d#1]
thanks friend , i have read your code. that's a great job. but i didnot know  the korean  code about PBSD operation. 대한건축학회, 철근콘크리트 건축구조물의 성능기반 내진설계를 위한 비선형해석모델(2021) [표 6-1] if you have these books pdf, please send to me ,thanks. my email is idealzeng@qq.com

**Comment by klm555** [comment]
This book was issued by the Architectural Institute of Korea(AIK) and is sold by the Architectural Institute of Korea. So I don't have the pdf version of this code(I wonder if it is legally possible to distribute it as a pdf version). I can partially provide what you need, but it seems impossible to provide all of them.

Also, I have to change this repository private soon because of my current company policy, so please be aware of this!
